In [1]:
import warnings
warnings.filterwarnings("ignore") # 버전 차이로 발생하는 warning ignore

In [2]:
import numpy as np

### 벡터와 행렬 선언

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
print(np.ones((1,5))) # 행, 열 순으로 입력
print(np.ones((3,2)))
print(np.zeros((1,5)))

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0. 0. 0.]]


In [10]:
# 주어진 범위 안에서 순차적으로 증가하는 리스트
# np.arange([start,] stop, [step,] dtype=None)

print(np.arange(10))
print(np.arange(3,7, dtype=np.float))
print(np.arange(3,10,2))

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [12]:
# 행렬 선언
mat1 = np.array([[1,2,3],[4,5,6]])

# random 초기화
mat2 = np.random.randint(low=1, high=10, size=(3,2)) # 1<=x<=10으로 3*2 matrix 생성
mat3 = np.random.rand(3,2) # 정규분포를 따르는

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[5 7]
 [2 7]
 [2 3]]
[[0.3208377  0.72574771]
 [0.69525834 0.78062883]
 [0.09903838 0.1458041 ]]


### np.reshape


In [16]:
mat1 = np.random.rand(6,3)
print(mat1)
print(mat1.reshape(1,-1)) # -1 == all
print(mat1.reshape(-1,1))
# 사이즈가 맞지 않을 경우 err 출력
# tensor(3차원 이상 행렬) 형태로도 가능
print(mat1.reshape(3,2,3))

[[0.69693716 0.13661608 0.4392578 ]
 [0.71941102 0.52096604 0.65485483]
 [0.41462064 0.58633762 0.54293966]
 [0.41138386 0.88189979 0.57622478]
 [0.4417939  0.67306935 0.04078381]
 [0.61535022 0.13911366 0.88037531]]
[[0.69693716 0.13661608 0.4392578  0.71941102 0.52096604 0.65485483
  0.41462064 0.58633762 0.54293966 0.41138386 0.88189979 0.57622478
  0.4417939  0.67306935 0.04078381 0.61535022 0.13911366 0.88037531]]
[[0.69693716]
 [0.13661608]
 [0.4392578 ]
 [0.71941102]
 [0.52096604]
 [0.65485483]
 [0.41462064]
 [0.58633762]
 [0.54293966]
 [0.41138386]
 [0.88189979]
 [0.57622478]
 [0.4417939 ]
 [0.67306935]
 [0.04078381]
 [0.61535022]
 [0.13911366]
 [0.88037531]]
[[[0.69693716 0.13661608 0.4392578 ]
  [0.71941102 0.52096604 0.65485483]]

 [[0.41462064 0.58633762 0.54293966]
  [0.41138386 0.88189979 0.57622478]]

 [[0.4417939  0.67306935 0.04078381]
  [0.61535022 0.13911366 0.88037531]]]


In [18]:
# matrix/tensor 형태에서의 slicing
mat2 = np.arange(24).reshape(-1,4)
print(mat2)
print(mat2[:1,:3])
print(mat2[3, 0:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[0 1 2]]
[12 13]


### 사칙연산


In [19]:
x = np.array([[1,3,5],[7,9,11],[13,15,17]])
y = np.array([[2,4,6],[8,10,12],[14,16,18]])

In [21]:
# 합
print(x.sum(axis=0))
print(x.sum(axis=1))
# 평균
print(x.mean(axis=0))
# 표준편차
print(x.std(axis=0))

[21 27 33]
[ 9 27 45]
[ 7.  9. 11.]
[4.89897949 4.89897949 4.89897949]


In [22]:
# transpose
print(x.T)

[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]


### 기타 연산

In [24]:
xx = np.random.rand(15)
print(xx)
print(xx.argsort()) #sorting이 되었을 때의 index를 알려줌
xx.sort()
print(xx)

[0.36597622 0.71488107 0.5041144  0.22325712 0.76690418 0.92805799
 0.92342408 0.12799277 0.62015107 0.80364652 0.62173123 0.40985854
 0.20853462 0.50828016 0.99040222]
[ 7 12  3  0 11  2 13  8 10  1  4  9  6  5 14]
[0.12799277 0.20853462 0.22325712 0.36597622 0.40985854 0.5041144
 0.50828016 0.62015107 0.62173123 0.71488107 0.76690418 0.80364652
 0.92342408 0.92805799 0.99040222]


## Pandas

In [26]:
import pandas as pd

### pandas series 만들기

In [27]:
pd_series = pd.Series(index=['a','b','c','d','e'], data=[1,2,3,4,5])
pd_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [29]:
# series의 기초 정보
print('차원:', pd_series.ndim)
print('형태: ', pd_series.shape)
print('총 원소의 수:', pd_series.size)

print('값:', pd_series.values)
print('인덱스:', pd_series.index)

차원: 1
형태:  (5,)
총 원소의 수: 5
값: [1 2 3 4 5]
인덱스: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


### index를 활용한 데이터 탐색

In [32]:
# loc(index 활용하여 access), iloc(integer location 활용하여 access)
print(pd_series.loc['a'])
print(pd_series.iloc[0])

print(pd_series.loc[['a','c']])
print(pd_series.iloc[[0,2]])

1
1
a    1
c    3
dtype: int64
a    1
c    3
dtype: int64


### 데이터 삭제

In [34]:
pd_series.drop('b') # 임시 삭제
print(pd_series)
pd_series.drop('b', inplace=True) # 삭제
print(pd_series)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
c    3
d    4
e    5
dtype: int64


### Dataframe 만들기

In [35]:
data = {
    'A': np.arange(15),
    'B': np.random.randint(low=0, high=15, size=(15)),
    'C': np.random.rand(15)
}

data_df = pd.DataFrame(data)

In [36]:
data_df

A   B         C
0    0   0  0.317687
1    1  13  0.877753
2    2   3  0.105179
3    3   7  0.282291
4    4   0  0.630528
5    5  12  0.578919
6    6   6  0.683821
7    7   3  0.357742
8    8  10  0.467328
9    9   4  0.263284
10  10  14  0.399247
11  11   9  0.104652
12  12   9  0.417277
13  13   8  0.467438
14  14  12  0.708228

In [40]:
data_df.head(5) # default 5개
data_df.tail(5) # default 5개
data_df.shape

(15, 3)

In [45]:
# indexing
print(data_df[1:3])
print()
print(data_df.loc[1][['B', 'C']])

   A   B         C
1  1  13  0.877753
2  2   3  0.105179

B    13.000000
C     0.877753
Name: 1, dtype: float64


### 기타

In [46]:
data_df.head()

A   B         C
0  0   0  0.317687
1  1  13  0.877753
2  2   3  0.105179
3  3   7  0.282291
4  4   0  0.630528

In [54]:
data_df['D'] = data_df['A'] >= 5
data_df.head()

A   B         C      D
0  0   0  0.317687  False
1  1  13  0.877753  False
2  2   3  0.105179  False
3  3   7  0.282291  False
4  4   0  0.630528  False

In [55]:
data_df.drop('D', axis=1, inplace=True) # 'D'라는 '열'을 inplace로 삭제하겠다
data_df.head()

A   B         C
0  0   0  0.317687
1  1  13  0.877753
2  2   3  0.105179
3  3   7  0.282291
4  4   0  0.630528

In [57]:
data_df.sort_index(axis=0, ascending=False) # index 기준으로 sorting하겠다 (내림차순)

A   B         C
14  14  12  0.708228
13  13   8  0.467438
12  12   9  0.417277
11  11   9  0.104652
10  10  14  0.399247
9    9   4  0.263284
8    8  10  0.467328
7    7   3  0.357742
6    6   6  0.683821
5    5  12  0.578919
4    4   0  0.630528
3    3   7  0.282291
2    2   3  0.105179
1    1  13  0.877753
0    0   0  0.317687